version: "3"
services:
  app:
    build: docker/nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./vendor:/app/vendor
      - ./src:/app/src
      - ./public:/app/public

  php:
    build: docker/php
    volumes:
      - ./:/app
    working_dir: /app

  composer:
    build: docker/composer
    links:
      - php
    restart: 'no'
    volumes:
      - ./:/app
    working_dir: /app
